### ISSUE TITLE
Error of linprog and code is "-2_4"

### ISSUE THREAD

**Issue by lzhou-xyz** [javierbarbero/DEAMATLAB#1]
错误使用 linprog (line 346)
LINPROG encountered an internal error that caused the solution to lose feasibility. We are sorry for the
inconvenience.

Please contact technical support for assistance with your problem, quoting the code "-2_4".

出错 dea (line 187)
                    [z, ~, exitflag] = linprog(f, [], [], Aeq, beq, lb, [], [], optimopts);

出错 deapro (line 49)
Efftemp = dea(X, Y, 'orient','io');

I don't know the reason when I use your code to do some analysis,would you please give me  some idea or help.

**Comment by javierbarbero** [comment]
Dear @alipeach2012,
This is an error generated by the MATLAB Optimization Toolbox. Why this error appears is a mistery, as MATLAB does not provide much information.

However, based in our experience, this errors can occur when the scale of the inputs X or the outputs Y is quite large. Dividing X and Y by 100, 1000, or a larger number usually solves the problem.

Another possible solution, or if the previous one does not work, is to change the algorithm for _linprog_ when calling the _dea_ function. Try to change the algorithm to 'interior-point' with the following code:
> opts = optimoptions('linprog','display','off', 'Algorithm','interior-point');
> io_ip = dea(X, Y, 'orient', 'io', 'secondstep', 0, 'optimopts', opts);

Please, let me know if this solves your problem.
Best.
