### ISSUE TITLE
linprog erorr

### ISSUE THREAD

**Issue by mohsenkondori** [javierbarbero/DEAMATLAB#2]
I have this error, I think must be revise the toolkit with correct usage of linprog.
Error using linprog
LINPROG(f,A,b,Aeq,beq,LB,UB,X0,OPTIONS) does not accept X0. Use LINPROG(f,A,b,Aeq,beq,LB,UB,OPTIONS) instead.

**Comment by javierbarbero** [comment]
Thanks for reporting. I have checked, and the problem occurs in version R2023a, as MATLAB has changed how the _linprog_ function works. It works fine in the previous MATLAB version. I will work on the code to ensure compatibility with the latest version.

**Comment by javierbarbero** [comment]
Done! Now it should work in MATLAB R2023a.
